### ISSUE TITLE
The end dot does not get parsed as part of ENUM defintion

### ISSUE THREAD

**Issue by gustason** [BalticAmadeus/OpenedgeAblFormatter#215]
For example,
``` abl
ENUM LiteraryMood FLAGS:
    define ENUM None = 0
                Joyful
                Melancholy
                Heroic
                Whimsical
                Epic
                JoyfulMelancholy = Joyful,Melancholy
                Tragic = Epic.
END ENUM.
```
The ```enum_statement``` gets parsed as ```ENUM LiteraryMood FLAGS: define ENUM None = 0 Joyful Melancholy Heroic Whimsical Epic JoyfulMelancholy```
Likewise, the ```enum_definition``` gets parsed as ```define ENUM None = 0 Joyful Melancholy Heroic Whimsical Epic JoyfulMelancholy = Joyful,Melancholy```
The ```.``` does not get parsed at all.

**Comment by eglekaz** [comment]
When I made the enum shorter, I see that end dot is parsed as a enum_definition. 
![Image](https://github.com/user-attachments/assets/1a501d75-50a4-43f1-9e6b-dcd4c704efbd)

From your description it looks like the information given by parser is just trimmed. Please check this again. If the issue is still there, we will submit the ticket
